In [1]:
import sys
from pathlib import Path

# Force notebook to recognize project root
import os
ROOT = Path(os.getcwd()).resolve().parents[0] # Um nível acima da pasta tests/
if str(ROOT) not in sys.path:
    sys.path.append(str(ROOT))

import pandas as pd
from scripts.inference_pipeline.inference import predict

Inference using project root: D:\Algoritmo-de-previsao-de-percentual-de-vitorias

In [2]:
sample = ROOT / "Classificacao_NBB" / "NBB_24_teams.csv"
df = pd.read_csv(sample)

df.head()

,Team,PPG,FGM,FGA,FG%,3PM,3PA,3P%,FTM,FTA,...,TOV%,STL%,BLK%,ORtg,DRtg,eDiff,Pace,Ast/TO,W's,Win %
0,Flamengo,85.2,30.3,65.1,0.466,10.4,29.7,0.351,14.1,18.6,...,14.3,10.7,5.4,117.5,107.1,10.4,72.2,1.6,34,0.723
1,Franca,85.1,29.9,61.7,0.485,9.9,27.0,0.368,15.3,19.1,...,14.3,10.1,7.0,118.0,106.1,11.9,71.9,1.5,37,0.725
2,Corinthians,82.3,29.4,65.8,0.447,10.5,30.5,0.343,13.0,17.4,...,14.6,7.7,4.6,112.0,109.5,2.5,73.1,1.5,21,0.512
3,Pato Basquete,81.3,29.3,65.1,0.450,11.3,30.7,0.367,11.5,15.4,...,15.2,8.4,4.3,111.4,115.4,-3.9,72.9,1.3,13,0.351
4,Minas,81.1,29.7,65.4,0.453,9.1,26.6,0.341,12.8,18.4,...,14.9,9.8,8.5,111.6,98.0,13.5,72.8,1.3,39,0.830

In [10]:
df_4 = df.iloc[[7]]

df_4

,Team,PPG,FGM,FGA,FG%,3PM,3PA,3P%,FTM,FTA,...,TOV%,STL%,BLK%,ORtg,DRtg,eDiff,Pace,Ast/TO,W's,Win %
7,Sao Jose Unimed Vinac,78.4,27.1,64.7,0.418,8.8,28.6,0.309,15.5,20.7,...,15.4,10.2,6.4,105.9,106.5,-0.6,73.7,1.3,18,0.474

In [11]:
percentual, total_vitorias = predict(df_4)

assert isinstance(percentual, float)
assert isinstance(total_vitorias, int)

print("✅ Teste de inferencia concluido.")
print(f"Percentual previsto de vitorias na temporada: {percentual:.2f}%")
print(f"Total previsto de vitorias na temporada: {total_vitorias}")

✅ Teste de inferencia concluido.
Percentual previsto de vitorias na temporada: 50.38%
Total previsto de vitorias na temporada: 18