# Simulação de confrontos diretos e de temporada regular
* Serão capturados os últimos elos registrados para cada time;
* Será testado o resultado de um confronto direto;
* Será simulado um torneio sem monte carlo, e com monte carlo.

In [1]:
import pandas as pd
import numpy as np
import plotly.express as px
from pathlib import Path

In [3]:
ROOT = Path.cwd().parent
df_elo = pd.read_csv(ROOT /'historico_nbb' / 'data' / 'historico_elo.csv')
nbb_26 = pd.read_csv(ROOT /'historico_nbb' / 'data' / 'calendario_26_nbb.csv')

In [4]:
df_elo.head()

   Season       Time          Elo
0    2016      Bauru  1488.577302
1    2016   Flamengo  1511.422698
2    2016  Pinheiros  1488.295954
3    2016    Vitória  1511.704046
4    2016      Minas  1507.678613

In [5]:
nbb_26.head()

   Season                    Casa      Visitante
0    2026                    Mogi    Corinthians
1    2026  Caxias do Sul Basquete       Cruzeiro
2    2026               UNIFACISA  Basket Osasco
3    2026                Flamengo          Bauru
4    2026                  Franca       São José

In [ ]:
df_elo['Time'].unique() # Vendo a lista dos times que estão no histórico de elo

<StringArray>
[                 'Bauru',               'Flamengo',              'Pinheiros',
                'Vitória',                  'Minas', 'Caxias do Sul Basquete',
                 'Franca',         'Macaé Basquete',      'Basquete Cearense',
          'Vasco da Gama',               'Brasília',           'Campo Mourão',
          'L. Sorocabana',                   'Mogi',             'Paulistano',
       'Joinville / AABJ',               'Botafogo',               'São José',
            'Corinthians',            'VipTech CMB',              'UNIFACISA',
          'Pato Basquete',              'São Paulo',       'Cerrado Basquete',
      'União Corinthians',              'Rio Claro',               'Cruzeiro',
          'Basket Osasco']
Length: 28, dtype: str

In [ ]:
nbb_26['Casa'].unique() # Vendo a lista dos times que estão no calendário da temporada 2026

<StringArray>
[                  'Mogi', 'Caxias do Sul Basquete',              'UNIFACISA',
               'Flamengo',                 'Franca',      'União Corinthians',
      'Basquete Cearense',                  'Bauru',          'Pato Basquete',
               'Brasília',            'Corinthians',                  'Minas',
               'Cruzeiro',              'Pinheiros',             'Paulistano',
               'São José',               'Botafogo',          'Basket Osasco']
Length: 18, dtype: str

In [10]:
# ===========================================================
# Coletando o último elo de cada time para a temporada 2026
# ===========================================================
elo_26 = df_elo[df_elo['Season'] == 2025].groupby('Time').last().reset_index()[['Time', 'Elo']]

elo_26

                      Time          Elo
0            Basket Osasco  1282.563945
1        Basquete Cearense  1244.923036
2                    Bauru  1594.751875
3                 Botafogo  1352.330969
4                 Brasília  1762.364740
5   Caxias do Sul Basquete  1492.955483
6              Corinthians  1771.403159
7                 Cruzeiro  1442.496105
8                 Flamengo  1714.594660
9                   Franca  1919.996108
10                   Minas  1712.333383
11                    Mogi  1700.371349
12           Pato Basquete  1246.169643
13              Paulistano  1648.457910
14               Pinheiros  1839.239403
15               Rio Claro  1398.984831
16                São José  1536.759499
17               UNIFACISA  1591.396521
18       União Corinthians  1512.682611
19           Vasco da Gama  1300.215660

In [11]:
# ===========================================================
# Simulando uma partida entre equipes selecionadas
# ===========================================================
bsb = elo_26[elo_26['Time'] == 'Brasília'].iloc[0]['Elo']
fla = elo_26[elo_26['Time'] == 'Flamengo'].iloc[0]['Elo']

prob_bsb = 1 / (1 + 10 ** ((fla - bsb) / 400))

result = np.random.choice(['Brasília', 'Flamengo'], p=[prob_bsb, 1 - prob_bsb])

print(f"Probabilidade de vitória do Brasília: {prob_bsb:.2%}")
print(f"Probabilidade de vitória do Flamengo: {1 - prob_bsb:.2%}")
print(f"Resultado da partida: {result}")

Probabilidade de vitória do Brasília: 56.83%
Probabilidade de vitória do Flamengo: 43.17%
Resultado da partida: Brasília

In [13]:
# ====================================================================================
# Simulando uma partida entre equipes selecionadas com vantagem de casa
# ====================================================================================
casa = 60
# Supondo que o Brasília jogue em casa
bsb = elo_26[elo_26['Time'] == 'Brasília'].iloc[0]['Elo']
fla = elo_26[elo_26['Time'] == 'Flamengo'].iloc[0]['Elo']
vtg =  (bsb + casa) - fla

prob_bsb = 1 / (1 + 10 ** ((-vtg) / 400))

result = np.random.choice(['Brasília', 'Flamengo'], p=[prob_bsb, 1 - prob_bsb])

print(f"Probabilidade de vitória do Brasília: {prob_bsb:.2%}")
print(f"Probabilidade de vitória do Flamengo: {1 - prob_bsb:.2%}")
print(f"Resultado da partida: {result}")

Probabilidade de vitória do Brasília: 65.03%
Probabilidade de vitória do Flamengo: 34.97%
Resultado da partida: Flamengo

In [14]:
# ====================================================================================
# Simulando uma partida entre equipes selecionadas com vantagem de casa várias vezes
# ====================================================================================
casa = 60
# Supondo que o Brasília jogue em casa
bsb = elo_26[elo_26['Time'] == 'Brasília'].iloc[0]['Elo']
fla = elo_26[elo_26['Time'] == 'Flamengo'].iloc[0]['Elo']
vtg =  (bsb + casa) - fla

prob_bsb = 1 / (1 + 10 ** ((-vtg) / 400))

result = []
for _ in range(5):  # Simula 5 partidas
    result.append(np.random.choice(['Brasília', 'Flamengo'], p=[prob_bsb, 1 - prob_bsb]))


print(f"Resultado da partida: {result}")

Resultado da partida: [np.str_('Brasília'), np.str_('Flamengo'), np.str_('Flamengo'), np.str_('Brasília'), np.str_('Flamengo')]

In [16]:
# ====================================================================================
# Simulando uma temporada da NBB 2026 com base no histórico de elo
# ====================================================================================
for row in nbb_26.itertuples():
    casa = row.Casa
    fora = row.Visitante
    
    elo_casa = elo_26[elo_26['Time'] == casa].iloc[0]['Elo']
    elo_fora = elo_26[elo_26['Time'] == fora].iloc[0]['Elo']
    vtg = (elo_casa + 60) - elo_fora  # Adicionando vantagem de casa de 60 pontos
    
    prob_casa = 1 / (1 + 10 ** ((-vtg) / 400))
    
    result = np.random.choice([casa, fora], p=[prob_casa, 1 - prob_casa])
    
    print(f"Jogo: {casa} vs {fora} | Resultado: {result} | Probabilidade de vitória do {casa}: {prob_casa:.2%}")

Jogo: Mogi vs Corinthians | Resultado: Corinthians | Probabilidade de vitória do Mogi: 48.41%
Jogo: Caxias do Sul Basquete vs Cruzeiro | Resultado: Cruzeiro | Probabilidade de vitória do Caxias do Sul Basquete: 65.38%
Jogo: UNIFACISA vs Basket Osasco | Resultado: UNIFACISA | Probabilidade de vitória do UNIFACISA: 89.31%
Jogo: Flamengo vs Bauru | Resultado: Flamengo | Probabilidade de vitória do Flamengo: 73.79%
Jogo: Franca vs São José | Resultado: Franca | Probabilidade de vitória do Franca: 92.77%
Jogo: União Corinthians vs Cruzeiro | Resultado: União Corinthians | Probabilidade de vitória do União Corinthians: 67.91%
Jogo: UNIFACISA vs Pinheiros | Resultado: Pinheiros | Probabilidade de vitória do UNIFACISA: 25.33%
Jogo: Caxias do Sul Basquete vs Minas | Resultado: Minas | Probabilidade de vitória do Caxias do Sul Basquete: 28.55%
Jogo: Basquete Cearense vs Basket Osasco | Resultado: Basquete Cearense | Probabilidade de vitória do Basquete Cearense: 53.21%
Jogo: Flamengo vs Botafogo | Resultado: Flamengo | Probabilidade de vitória do Flamengo: 91.91%
Jogo: Bauru vs São José | Resultado: Bauru | Probabilidade de vitória do Bauru: 66.36%
Jogo: Franca vs Mogi | Resultado: Franca | Probabilidade de vitória do Franca: 83.34%
Jogo: Pato Basquete vs Paulistano | Resultado: Paulistano | Probabilidade de vitória do Pato Basquete: 12.23%
Jogo: União Corinthians vs Minas | Resultado: União Corinthians | Probabilidade de vitória do União Corinthians: 30.92%
Jogo: Basquete Cearense vs Pinheiros | Resultado: Pinheiros | Probabilidade de vitória do Basquete Cearense: 4.41%
Jogo: Brasília vs Corinthians | Resultado: Brasília | Probabilidade de vitória do Brasília: 57.28%
Jogo: Bauru vs Mogi | Resultado: Mogi | Probabilidade de vitória do Bauru: 43.47%
Jogo: Brasília vs Paulistano | Resultado: Brasília | Probabilidade de vitória do Brasília: 73.13%
Jogo: Pato Basquete vs Botafogo | Resultado: Pato Basquete | Probabilidade de vitória do Pato Basquete: 43.40%
Jogo: Corinthians vs Franca | Resultado: Corinthians | Probabilidade de vitória do Corinthians: 37.52%
Jogo: Mogi vs UNIFACISA | Resultado: Mogi | Probabilidade de vitória do Mogi: 72.57%
Jogo: Minas vs Pato Basquete | Resultado: Minas | Probabilidade de vitória do Minas: 95.39%
Jogo: Cruzeiro vs Brasília | Resultado: Brasília | Probabilidade de vitória do Cruzeiro: 18.30%
Jogo: Pinheiros vs União Corinthians | Resultado: União Corinthians | Probabilidade de vitória do Pinheiros: 90.25%
Jogo: Paulistano vs Franca | Resultado: Franca | Probabilidade de vitória do Paulistano: 22.83%
Jogo: São José vs UNIFACISA | Resultado: UNIFACISA | Probabilidade de vitória do São José: 50.77%
Jogo: Botafogo vs Caxias do Sul Basquete | Resultado: Botafogo | Probabilidade de vitória do Botafogo: 38.60%
Jogo: Minas vs Brasília | Resultado: Minas | Probabilidade de vitória do Minas: 51.43%
Jogo: Cruzeiro vs Pato Basquete | Resultado: Cruzeiro | Probabilidade de vitória do Cruzeiro: 81.39%
Jogo: Basket Osasco vs Pinheiros | Resultado: Pinheiros | Probabilidade de vitória do Basket Osasco: 5.42%
Jogo: Paulistano vs Bauru | Resultado: Paulistano | Probabilidade de vitória do Paulistano: 65.80%
Jogo: Botafogo vs União Corinthians | Resultado: União Corinthians | Probabilidade de vitória do Botafogo: 35.95%
Jogo: Flamengo vs Caxias do Sul Basquete | Resultado: Flamengo | Probabilidade de vitória do Flamengo: 83.50%
Jogo: Flamengo vs União Corinthians | Resultado: Flamengo | Probabilidade de vitória do Flamengo: 81.87%
Jogo: Pinheiros vs Caxias do Sul Basquete | Resultado: Pinheiros | Probabilidade de vitória do Pinheiros: 91.20%
Jogo: Brasília vs Botafogo | Resultado: Brasília | Probabilidade de vitória do Brasília: 93.74%
Jogo: São José vs Basquete Cearense | Resultado: São José | Probabilidade de vitória do São José: 88.34%
Jogo: Bauru vs Cruzeiro | Resultado: Bauru | Probabilidade de vitória do Bauru: 77.24%
Jogo: Franca vs Minas | Resultado: Franca | Probabilidade de vitória do Franca: 82.36%
Jogo: UNIFACISA vs Paulistano | Resultado: UNIFACISA | Probabilidade de vitória do UNIFACISA: 50.42%
Jogo: Mogi vs Basquete Cearense | Resultado: Mogi | Probabilidade de vitória do Mogi: 95.11%
Jogo: Brasília vs Flamengo | Resultado: Brasília | Probabilidade de vitória do Brasília: 65.03%
Jogo: Bauru vs Minas | Resultado: Bauru | Probabilidade de vitória do Bauru: 41.79%
Jogo: Franca vs Cruzeiro | Resultado: Cruzeiro | Probabilidade de vitória do Franca: 95.66%
Jogo: Basket Osasco vs São José | Resultado: São José | Probabilidade de vitória do Basket Osasco: 24.64%
Jogo: UNIFACISA vs Corinthians | Resultado: UNIFACISA | Probabilidade de vitória do UNIFACISA: 33.39%
Jogo: Basquete Cearense vs Paulistano | Resultado: Paulistano | Probabilidade de vitória do Basquete Cearense: 12.16%
Jogo: Pinheiros vs São José | Resultado: Pinheiros | Probabilidade de vitória do Pinheiros: 88.96%
Jogo: Caxias do Sul Basquete vs Brasília | Resultado: Brasília | Probabilidade de vitória do Caxias do Sul Basquete: 23.05%
Jogo: Pato Basquete vs Flamengo | Resultado: Flamengo | Probabilidade de vitória do Pato Basquete: 8.70%
Jogo: Pato Basquete vs Bauru | Resultado: Bauru | Probabilidade de vitória do Pato Basquete: 15.96%
Jogo: União Corinthians vs Brasília | Resultado: União Corinthians | Probabilidade de vitória do União Corinthians: 25.13%
Jogo: Basquete Cearense vs Corinthians | Resultado: Corinthians | Probabilidade de vitória do Basquete Cearense: 6.38%
Jogo: Pinheiros vs Mogi | Resultado: Pinheiros | Probabilidade de vitória do Pinheiros: 75.86%
Jogo: Flamengo vs Franca | Resultado: Franca | Probabilidade de vitória do Flamengo: 30.22%
Jogo: Minas vs UNIFACISA | Resultado: Minas | Probabilidade de vitória do Minas: 73.92%
Jogo: Caxias do Sul Basquete vs Pato Basquete | Resultado: Caxias do Sul Basquete | Probabilidade de vitória do Caxias do Sul Basquete: 85.40%
Jogo: Botafogo vs Franca | Resultado: Franca | Probabilidade de vitória do Botafogo: 5.11%
Jogo: Corinthians vs Pinheiros | Resultado: Pinheiros | Probabilidade de vitória do Corinthians: 48.87%
Jogo: Basket Osasco vs Mogi | Resultado: Mogi | Probabilidade de vitória do Basket Osasco: 11.31%
Jogo: Cruzeiro vs UNIFACISA | Resultado: Cruzeiro | Probabilidade de vitória do Cruzeiro: 37.48%
Jogo: São José vs Paulistano | Resultado: Paulistano | Probabilidade de vitória do São José: 42.61%
Jogo: Corinthians vs Basket Osasco | Resultado: Corinthians | Probabilidade de vitória do Corinthians: 95.93%
Jogo: União Corinthians vs Pato Basquete | Resultado: União Corinthians | Probabilidade de vitória do União Corinthians: 86.76%
Jogo: Minas vs Basquete Cearense | Resultado: Minas | Probabilidade de vitória do Minas: 95.42%
Jogo: Cruzeiro vs Basquete Cearense | Resultado: Basquete Cearense | Probabilidade de vitória do Cruzeiro: 81.50%
Jogo: São José vs Mogi | Resultado: Mogi | Probabilidade de vitória do São José: 35.52%
Jogo: UNIFACISA vs Botafogo | Resultado: UNIFACISA | Probabilidade de vitória do UNIFACISA: 84.83%
Jogo: Corinthians vs Paulistano | Resultado: Corinthians | Probabilidade de vitória do Corinthians: 74.14%
Jogo: Franca vs Caxias do Sul Basquete | Resultado: Franca | Probabilidade de vitória do Franca: 94.29%
Jogo: Pato Basquete vs Corinthians | Resultado: Pato Basquete | Probabilidade de vitória do Pato Basquete: 6.43%
Jogo: UNIFACISA vs Flamengo | Resultado: UNIFACISA | Probabilidade de vitória do UNIFACISA: 41.00%
Jogo: Pinheiros vs Cruzeiro | Resultado: Pinheiros | Probabilidade de vitória do Pinheiros: 93.27%
Jogo: Basket Osasco vs Minas | Resultado: Basket Osasco | Probabilidade de vitória do Basket Osasco: 10.64%
Jogo: Franca vs União Corinthians | Resultado: Franca | Probabilidade de vitória do Franca: 93.64%
Jogo: Bauru vs Caxias do Sul Basquete | Resultado: Bauru | Probabilidade de vitória do Bauru: 71.74%
Jogo: Basquete Cearense vs Botafogo | Resultado: Botafogo | Probabilidade de vitória do Basquete Cearense: 43.22%
Jogo: Pinheiros vs Minas | Resultado: Pinheiros | Probabilidade de vitória do Pinheiros: 74.57%
Jogo: Basket Osasco vs Cruzeiro | Resultado: Cruzeiro | Probabilidade de vitória do Basket Osasco: 36.00%
Jogo: Basquete Cearense vs Flamengo | Resultado: Flamengo | Probabilidade de vitória do Basquete Cearense: 8.64%
Jogo: São José vs Corinthians | Resultado: Corinthians | Probabilidade de vitória do São José: 26.79%
Jogo: Brasília vs Pato Basquete | Resultado: Brasília | Probabilidade de vitória do Brasília: 96.50%
Jogo: Mogi vs Paulistano | Resultado: Mogi | Probabilidade de vitória do Mogi: 65.57%
Jogo: Bauru vs União Corinthians | Resultado: Bauru | Probabilidade de vitória do Bauru: 69.38%
Jogo: Franca vs Bauru | Resultado: Franca | Probabilidade de vitória do Franca: 90.18%
Jogo: Pato Basquete vs Pinheiros | Resultado: Pinheiros | Probabilidade de vitória do Pato Basquete: 4.44%
Jogo: Caxias do Sul Basquete vs UNIFACISA | Resultado: Caxias do Sul Basquete | Probabilidade de vitória do Caxias do Sul Basquete: 44.49%
Jogo: União Corinthians vs Basquete Cearense | Resultado: União Corinthians | Probabilidade de vitória do União Corinthians: 86.84%
Jogo: São José vs Botafogo | Resultado: Botafogo | Probabilidade de vitória do São José: 80.33%
Jogo: Paulistano vs Basket Osasco | Resultado: Paulistano | Probabilidade de vitória do Paulistano: 92.07%
Jogo: Cruzeiro vs Minas | Resultado: Minas | Probabilidade de vitória do Cruzeiro: 23.01%
Jogo: Caxias do Sul Basquete vs Basquete Cearense | Resultado: Caxias do Sul Basquete | Probabilidade de vitória do Caxias do Sul Basquete: 85.49%
Jogo: União Corinthians vs UNIFACISA | Resultado: UNIFACISA | Probabilidade de vitória do União Corinthians: 47.31%
Jogo: Paulistano vs Pinheiros | Resultado: Pinheiros | Probabilidade de vitória do Paulistano: 32.02%
Jogo: Pato Basquete vs Franca | Resultado: Franca | Probabilidade de vitória do Pato Basquete: 2.84%
Jogo: Minas vs São José | Resultado: São José | Probabilidade de vitória do Minas: 79.51%
Jogo: Cruzeiro vs São José | Resultado: São José | Probabilidade de vitória do Cruzeiro: 45.09%
Jogo: Basket Osasco vs União Corinthians | Resultado: União Corinthians | Probabilidade de vitória do Basket Osasco: 27.30%
Jogo: Basquete Cearense vs Pato Basquete | Resultado: Basquete Cearense | Probabilidade de vitória do Basquete Cearense: 58.38%
Jogo: Botafogo vs Bauru | Resultado: Botafogo | Probabilidade de vitória do Botafogo: 25.92%
Jogo: UNIFACISA vs Brasília | Resultado: UNIFACISA | Probabilidade de vitória do UNIFACISA: 34.55%
Jogo: Mogi vs Flamengo | Resultado: Flamengo | Probabilidade de vitória do Mogi: 56.55%
Jogo: Basket Osasco vs Caxias do Sul Basquete | Resultado: Caxias do Sul Basquete | Probabilidade de vitória do Basket Osasco: 29.61%
Jogo: Corinthians vs Bauru | Resultado: Corinthians | Probabilidade de vitória do Corinthians: 79.61%
Jogo: São José vs Flamengo | Resultado: São José | Probabilidade de vitória do São José: 33.66%
Jogo: Mogi vs Botafogo | Resultado: Mogi | Probabilidade de vitória do Mogi: 91.28%
Jogo: Pato Basquete vs Basket Osasco | Resultado: Basket Osasco | Probabilidade de vitória do Pato Basquete: 53.39%
Jogo: Basquete Cearense vs Brasília | Resultado: Brasília | Probabilidade de vitória do Basquete Cearense: 6.70%
Jogo: Caxias do Sul Basquete vs União Corinthians | Resultado: Caxias do Sul Basquete | Probabilidade de vitória do Caxias do Sul Basquete: 55.77%
Jogo: Botafogo vs Paulistano | Resultado: Paulistano | Probabilidade de vitória do Botafogo: 20.44%
Jogo: Flamengo vs Corinthians | Resultado: Flamengo | Probabilidade de vitória do Flamengo: 50.46%
Jogo: Bauru vs UNIFACISA | Resultado: UNIFACISA | Probabilidade de vitória do Bauru: 59.02%
Jogo: Cruzeiro vs Mogi | Resultado: Mogi | Probabilidade de vitória do Cruzeiro: 24.25%
Jogo: Brasília vs Basket Osasco | Resultado: Brasília | Probabilidade de vitória do Brasília: 95.72%
Jogo: União Corinthians vs São José | Resultado: União Corinthians | Probabilidade de vitória do União Corinthians: 55.15%
Jogo: Botafogo vs Corinthians | Resultado: Corinthians | Probabilidade de vitória do Botafogo: 11.23%
Jogo: Flamengo vs Paulistano | Resultado: Paulistano | Probabilidade de vitória do Flamengo: 67.39%
Jogo: Minas vs Mogi | Resultado: Minas | Probabilidade de vitória do Minas: 60.21%
Jogo: Bauru vs Basquete Cearense | Resultado: Bauru | Probabilidade de vitória do Bauru: 91.37%
Jogo: Franca vs UNIFACISA | Resultado: Franca | Probabilidade de vitória do Franca: 90.35%
Jogo: Brasília vs Pinheiros | Resultado: Brasília | Probabilidade de vitória do Brasília: 47.57%
Jogo: Caxias do Sul Basquete vs São José | Resultado: Caxias do Sul Basquete | Probabilidade de vitória do Caxias do Sul Basquete: 52.33%
Jogo: Franca vs Basquete Cearense | Resultado: Franca | Probabilidade de vitória do Franca: 98.57%
Jogo: Caxias do Sul Basquete vs Mogi | Resultado: Mogi | Probabilidade de vitória do Caxias do Sul Basquete: 29.97%
Jogo: Paulistano vs Minas | Resultado: Minas | Probabilidade de vitória do Paulistano: 49.44%
Jogo: Botafogo vs Pinheiros | Resultado: Pinheiros | Probabilidade de vitória do Botafogo: 7.89%
Jogo: Flamengo vs Basket Osasco | Resultado: Flamengo | Probabilidade de vitória do Flamengo: 94.44%
Jogo: Corinthians vs Cruzeiro | Resultado: Corinthians | Probabilidade de vitória do Corinthians: 90.37%
Jogo: Brasília vs Bauru | Resultado: Brasília | Probabilidade de vitória do Brasília: 78.76%
Jogo: UNIFACISA vs Pato Basquete | Resultado: UNIFACISA | Probabilidade de vitória do UNIFACISA: 91.15%
Jogo: União Corinthians vs Mogi | Resultado: Mogi | Probabilidade de vitória do União Corinthians: 32.41%
Jogo: Paulistano vs Cruzeiro | Resultado: Paulistano | Probabilidade de vitória do Paulistano: 82.22%
Jogo: Botafogo vs Basket Osasco | Resultado: Botafogo | Probabilidade de vitória do Botafogo: 67.85%
Jogo: Flamengo vs Pinheiros | Resultado: Flamengo | Probabilidade de vitória do Flamengo: 40.80%
Jogo: Corinthians vs Minas | Resultado: Minas | Probabilidade de vitória do Corinthians: 66.49%
Jogo: Brasília vs Franca | Resultado: Brasília | Probabilidade de vitória do Brasília: 36.31%
Jogo: Corinthians vs União Corinthians | Resultado: Corinthians | Probabilidade de vitória do Corinthians: 86.23%
Jogo: Paulistano vs Caxias do Sul Basquete | Resultado: Paulistano | Probabilidade de vitória do Paulistano: 77.57%
Jogo: Cruzeiro vs Botafogo | Resultado: Botafogo | Probabilidade de vitória do Cruzeiro: 70.36%
Jogo: São José vs Brasília | Resultado: Brasília | Probabilidade de vitória do São José: 27.82%
Jogo: Pinheiros vs Bauru | Resultado: Pinheiros | Probabilidade de vitória do Pinheiros: 85.23%
Jogo: Basket Osasco vs Franca | Resultado: Franca | Probabilidade de vitória do Basket Osasco: 3.48%
Jogo: Minas vs Flamengo | Resultado: Flamengo | Probabilidade de vitória do Minas: 58.23%
Jogo: Mogi vs Pato Basquete | Resultado: Mogi | Probabilidade de vitória do Mogi: 95.07%
Jogo: UNIFACISA vs Basquete Cearense | Resultado: UNIFACISA | Probabilidade de vitória do UNIFACISA: 91.21%
Jogo: Minas vs Botafogo | Resultado: Minas | Probabilidade de vitória do Minas: 91.82%
Jogo: Paulistano vs União Corinthians | Resultado: Paulistano | Probabilidade de vitória do Paulistano: 75.53%
Jogo: Cruzeiro vs Flamengo | Resultado: Flamengo | Probabilidade de vitória do Cruzeiro: 22.78%
Jogo: São José vs Pato Basquete | Resultado: São José | Probabilidade de vitória do São José: 88.27%
Jogo: Corinthians vs Caxias do Sul Basquete | Resultado: Caxias do Sul Basquete | Probabilidade de vitória do Corinthians: 87.53%
Jogo: Mogi vs Brasília | Resultado: Brasília | Probabilidade de vitória do Mogi: 49.71%
Jogo: Pinheiros vs Franca | Resultado: Pinheiros | Probabilidade de vitória do Pinheiros: 47.02%
Jogo: Basket Osasco vs Bauru | Resultado: Bauru | Probabilidade de vitória do Basket Osasco: 18.97%