# Simulação de confrontos diretos e de temporada regular
* Serão capturados os últimos elos registrados para cada time;
* Será testado o resultado de um confronto direto;
* Será simulado um torneio sem monte carlo, e com monte carlo.

In [1]:
import pandas as pd
import numpy as np
import plotly.express as px
from pathlib import Path

In [2]:
ROOT = Path.cwd().parent
df_elo = pd.read_csv(ROOT /'historico_nbb' / 'data' / 'historico_elo.csv')
nbb_26 = pd.read_csv(ROOT /'historico_nbb' / 'data' / 'calendario_26_nbb.csv')

In [3]:
df_elo.head()

   Season       Time          Elo
0    2016      Bauru  1489.551101
1    2016   Flamengo  1510.448899
2    2016  Pinheiros  1489.293738
3    2016    Vitória  1510.706262
4    2016      Minas  1508.842695

In [4]:
nbb_26.head()

   Season                    Casa      Visitante
0    2026                    Mogi    Corinthians
1    2026  Caxias do Sul Basquete       Cruzeiro
2    2026               UNIFACISA  Basket Osasco
3    2026                Flamengo          Bauru
4    2026                  Franca       São José

In [5]:
df_elo['Time'].unique() # Vendo a lista dos times que estão no histórico de elo

<StringArray>
[                 'Bauru',               'Flamengo',              'Pinheiros',
                'Vitória',                  'Minas', 'Caxias do Sul Basquete',
                 'Franca',         'Macaé Basquete',      'Basquete Cearense',
          'Vasco da Gama',               'Brasília',           'Campo Mourão',
          'L. Sorocabana',                   'Mogi',             'Paulistano',
       'Joinville / AABJ',               'Botafogo',               'São José',
            'Corinthians',            'VipTech CMB',              'UNIFACISA',
          'Pato Basquete',              'São Paulo',       'Cerrado Basquete',
      'União Corinthians',              'Rio Claro',               'Cruzeiro',
          'Basket Osasco']
Length: 28, dtype: str

In [6]:
nbb_26['Casa'].unique() # Vendo a lista dos times que estão no calendário da temporada 2026

<StringArray>
[                  'Mogi', 'Caxias do Sul Basquete',              'UNIFACISA',
               'Flamengo',                 'Franca',      'União Corinthians',
      'Basquete Cearense',                  'Bauru',          'Pato Basquete',
               'Brasília',            'Corinthians',                  'Minas',
               'Cruzeiro',              'Pinheiros',             'Paulistano',
               'São José',               'Botafogo',          'Basket Osasco']
Length: 18, dtype: str

In [7]:
# ===========================================================
# Coletando o último elo de cada time para a temporada 2026
# ===========================================================
elo_26 = df_elo[df_elo['Season'] == 2025].groupby('Time').last().reset_index()[['Time', 'Elo']]

elo_26

                      Time          Elo
0            Basket Osasco  1290.285361
1        Basquete Cearense  1254.020408
2                    Bauru  1586.872178
3                 Botafogo  1359.344906
4                 Brasília  1760.525917
5   Caxias do Sul Basquete  1499.711879
6              Corinthians  1762.702554
7                 Cruzeiro  1444.275302
8                 Flamengo  1708.818785
9                   Franca  1910.205789
10                   Minas  1701.836481
11                    Mogi  1700.211726
12           Pato Basquete  1253.292558
13              Paulistano  1641.573135
14               Pinheiros  1828.027639
15               Rio Claro  1405.363947
16                São José  1531.172725
17               UNIFACISA  1588.290432
18       União Corinthians  1514.853433
19           Vasco da Gama  1308.418338

In [8]:
# ===========================================================
# Simulando uma partida entre equipes selecionadas
# ===========================================================
bsb = elo_26[elo_26['Time'] == 'Brasília'].iloc[0]['Elo']
fla = elo_26[elo_26['Time'] == 'Flamengo'].iloc[0]['Elo']

prob_bsb = 1 / (1 + 10 ** ((fla - bsb) / 400))

result = np.random.choice(['Brasília', 'Flamengo'], p=[prob_bsb, 1 - prob_bsb])

print(f"Probabilidade de vitória do Brasília: {prob_bsb:.2%}")
print(f"Probabilidade de vitória do Flamengo: {1 - prob_bsb:.2%}")
print(f"Resultado da partida: {result}")

Probabilidade de vitória do Brasília: 57.39%
Probabilidade de vitória do Flamengo: 42.61%
Resultado da partida: Brasília

In [9]:
# ====================================================================================
# Simulando uma partida entre equipes selecionadas com vantagem de casa
# ====================================================================================
casa = 60
# Supondo que o Brasília jogue em casa
bsb = elo_26[elo_26['Time'] == 'Brasília'].iloc[0]['Elo']
fla = elo_26[elo_26['Time'] == 'Flamengo'].iloc[0]['Elo']
vtg =  (bsb + casa) - fla

prob_bsb = 1 / (1 + 10 ** ((-vtg) / 400))

result = np.random.choice(['Brasília', 'Flamengo'], p=[prob_bsb, 1 - prob_bsb])

print(f"Probabilidade de vitória do Brasília: {prob_bsb:.2%}")
print(f"Probabilidade de vitória do Flamengo: {1 - prob_bsb:.2%}")
print(f"Resultado da partida: {result}")

Probabilidade de vitória do Brasília: 65.54%
Probabilidade de vitória do Flamengo: 34.46%
Resultado da partida: Brasília

In [10]:
# ====================================================================================
# Simulando uma partida entre equipes selecionadas com vantagem de casa várias vezes
# ====================================================================================
casa = 60
# Supondo que o Brasília jogue em casa
bsb = elo_26[elo_26['Time'] == 'Brasília'].iloc[0]['Elo']
fla = elo_26[elo_26['Time'] == 'Flamengo'].iloc[0]['Elo']
vtg =  (bsb + casa) - fla

prob_bsb = 1 / (1 + 10 ** ((-vtg) / 400))

result = []
for _ in range(5):  # Simula 5 partidas
    result.append(np.random.choice(['Brasília', 'Flamengo'], p=[prob_bsb, 1 - prob_bsb]))


print(f"Resultado da partida: {result}")

Resultado da partida: [np.str_('Flamengo'), np.str_('Brasília'), np.str_('Brasília'), np.str_('Flamengo'), np.str_('Brasília')]

In [11]:
# ====================================================================================
# Simulando uma temporada da NBB 2026 com base no histórico de elo
# ====================================================================================
for row in nbb_26.itertuples():
    casa = row.Casa
    fora = row.Visitante
    
    elo_casa = elo_26[elo_26['Time'] == casa].iloc[0]['Elo']
    elo_fora = elo_26[elo_26['Time'] == fora].iloc[0]['Elo']
    vtg = (elo_casa + 60) - elo_fora  # Adicionando vantagem de casa de 60 pontos
    
    prob_casa = 1 / (1 + 10 ** ((-vtg) / 400))
    
    result = np.random.choice([casa, fora], p=[prob_casa, 1 - prob_casa])
    
    print(f"Jogo: {casa} vs {fora} | Resultado: {result} | Probabilidade de vitória do {casa}: {prob_casa:.2%}")

Jogo: Mogi vs Corinthians | Resultado: Corinthians | Probabilidade de vitória do Mogi: 49.64%
Jogo: Caxias do Sul Basquete vs Cruzeiro | Resultado: Caxias do Sul Basquete | Probabilidade de vitória do Caxias do Sul Basquete: 66.03%
Jogo: UNIFACISA vs Basket Osasco | Resultado: UNIFACISA | Probabilidade de vitória do UNIFACISA: 88.70%
Jogo: Flamengo vs Bauru | Resultado: Flamengo | Probabilidade de vitória do Flamengo: 74.03%
Jogo: Franca vs São José | Resultado: Franca | Probabilidade de vitória do Franca: 92.60%
Jogo: União Corinthians vs Cruzeiro | Resultado: União Corinthians | Probabilidade de vitória do União Corinthians: 67.95%
Jogo: UNIFACISA vs Pinheiros | Resultado: Pinheiros | Probabilidade de vitória do UNIFACISA: 26.22%
Jogo: Caxias do Sul Basquete vs Minas | Resultado: Minas | Probabilidade de vitória do Caxias do Sul Basquete: 30.62%
Jogo: Basquete Cearense vs Basket Osasco | Resultado: Basquete Cearense | Probabilidade de vitória do Basquete Cearense: 53.41%
Jogo: Flamengo vs Botafogo | Resultado: Flamengo | Probabilidade de vitória do Flamengo: 91.35%
Jogo: Bauru vs São José | Resultado: São José | Probabilidade de vitória do Bauru: 66.06%
Jogo: Franca vs Mogi | Resultado: Franca | Probabilidade de vitória do Franca: 82.55%
Jogo: Pato Basquete vs Paulistano | Resultado: Pato Basquete | Probabilidade de vitória do Pato Basquete: 13.13%
Jogo: União Corinthians vs Minas | Resultado: Minas | Probabilidade de vitória do União Corinthians: 32.50%
Jogo: Basquete Cearense vs Pinheiros | Resultado: Pinheiros | Probabilidade de vitória do Basquete Cearense: 4.93%
Jogo: Brasília vs Corinthians | Resultado: Corinthians | Probabilidade de vitória do Brasília: 58.25%
Jogo: Bauru vs Mogi | Resultado: Mogi | Probabilidade de vitória do Bauru: 42.38%
Jogo: Brasília vs Paulistano | Resultado: Brasília | Probabilidade de vitória do Brasília: 73.69%
Jogo: Pato Basquete vs Botafogo | Resultado: Botafogo | Probabilidade de vitória do Pato Basquete: 43.41%
Jogo: Corinthians vs Franca | Resultado: Franca | Probabilidade de vitória do Corinthians: 37.67%
Jogo: Mogi vs UNIFACISA | Resultado: UNIFACISA | Probabilidade de vitória do Mogi: 72.90%
Jogo: Minas vs Pato Basquete | Resultado: Minas | Probabilidade de vitória do Minas: 94.92%
Jogo: Cruzeiro vs Brasília | Resultado: Brasília | Probabilidade de vitória do Cruzeiro: 18.62%
Jogo: Pinheiros vs União Corinthians | Resultado: Pinheiros | Probabilidade de vitória do Pinheiros: 89.55%
Jogo: Paulistano vs Franca | Resultado: Paulistano | Probabilidade de vitória do Paulistano: 23.13%
Jogo: São José vs UNIFACISA | Resultado: UNIFACISA | Probabilidade de vitória do São José: 50.41%
Jogo: Botafogo vs Caxias do Sul Basquete | Resultado: Caxias do Sul Basquete | Probabilidade de vitória do Botafogo: 38.64%
Jogo: Minas vs Brasília | Resultado: Brasília | Probabilidade de vitória do Minas: 50.19%
Jogo: Cruzeiro vs Pato Basquete | Resultado: Pato Basquete | Probabilidade de vitória do Cruzeiro: 80.92%
Jogo: Basket Osasco vs Pinheiros | Resultado: Pinheiros | Probabilidade de vitória do Basket Osasco: 6.01%
Jogo: Paulistano vs Bauru | Resultado: Bauru | Probabilidade de vitória do Paulistano: 65.93%
Jogo: Botafogo vs União Corinthians | Resultado: União Corinthians | Probabilidade de vitória do Botafogo: 36.59%
Jogo: Flamengo vs Caxias do Sul Basquete | Resultado: Caxias do Sul Basquete | Probabilidade de vitória do Flamengo: 82.48%
Jogo: Flamengo vs União Corinthians | Resultado: Flamengo | Probabilidade de vitória do Flamengo: 81.18%
Jogo: Pinheiros vs Caxias do Sul Basquete | Resultado: Pinheiros | Probabilidade de vitória do Pinheiros: 90.34%
Jogo: Brasília vs Botafogo | Resultado: Brasília | Probabilidade de vitória do Brasília: 93.43%
Jogo: São José vs Basquete Cearense | Resultado: São José | Probabilidade de vitória do São José: 87.44%
Jogo: Bauru vs Cruzeiro | Resultado: Bauru | Probabilidade de vitória do Bauru: 76.25%
Jogo: Franca vs Minas | Resultado: Minas | Probabilidade de vitória do Franca: 82.42%
Jogo: UNIFACISA vs Paulistano | Resultado: UNIFACISA | Probabilidade de vitória do UNIFACISA: 50.97%
Jogo: Mogi vs Basquete Cearense | Resultado: Mogi | Probabilidade de vitória do Mogi: 94.85%
Jogo: Brasília vs Flamengo | Resultado: Brasília | Probabilidade de vitória do Brasília: 65.54%
Jogo: Bauru vs Minas | Resultado: Bauru | Probabilidade de vitória do Bauru: 42.16%
Jogo: Franca vs Cruzeiro | Resultado: Franca | Probabilidade de vitória do Franca: 95.38%
Jogo: Basket Osasco vs São José | Resultado: São José | Probabilidade de vitória do Basket Osasco: 26.09%
Jogo: UNIFACISA vs Corinthians | Resultado: UNIFACISA | Probabilidade de vitória do UNIFACISA: 34.11%
Jogo: Basquete Cearense vs Paulistano | Resultado: Paulistano | Probabilidade de vitória do Basquete Cearense: 13.18%
Jogo: Pinheiros vs São José | Resultado: Pinheiros | Probabilidade de vitória do Pinheiros: 88.64%
Jogo: Caxias do Sul Basquete vs Brasília | Resultado: Brasília | Probabilidade de vitória do Caxias do Sul Basquete: 23.94%
Jogo: Pato Basquete vs Flamengo | Resultado: Flamengo | Probabilidade de vitória do Pato Basquete: 9.31%
Jogo: Pato Basquete vs Bauru | Resultado: Pato Basquete | Probabilidade de vitória do Pato Basquete: 17.15%
Jogo: União Corinthians vs Brasília | Resultado: Brasília | Probabilidade de vitória do União Corinthians: 25.56%
Jogo: Basquete Cearense vs Corinthians | Resultado: Corinthians | Probabilidade de vitória do Basquete Cearense: 7.03%
Jogo: Pinheiros vs Mogi | Resultado: Mogi | Probabilidade de vitória do Pinheiros: 74.67%
Jogo: Flamengo vs Franca | Resultado: Franca | Probabilidade de vitória do Flamengo: 30.71%
Jogo: Minas vs UNIFACISA | Resultado: Minas | Probabilidade de vitória do Minas: 73.09%
Jogo: Caxias do Sul Basquete vs Pato Basquete | Resultado: Caxias do Sul Basquete | Probabilidade de vitória do Caxias do Sul Basquete: 85.37%
Jogo: Botafogo vs Franca | Resultado: Franca | Probabilidade de vitória do Botafogo: 5.60%
Jogo: Corinthians vs Pinheiros | Resultado: Pinheiros | Probabilidade de vitória do Corinthians: 49.23%
Jogo: Basket Osasco vs Mogi | Resultado: Mogi | Probabilidade de vitória do Basket Osasco: 11.77%
Jogo: Cruzeiro vs UNIFACISA | Resultado: Cruzeiro | Probabilidade de vitória do Cruzeiro: 38.14%
Jogo: São José vs Paulistano | Resultado: São José | Probabilidade de vitória do São José: 42.80%
Jogo: Corinthians vs Basket Osasco | Resultado: Corinthians | Probabilidade de vitória do Corinthians: 95.54%
Jogo: União Corinthians vs Pato Basquete | Resultado: União Corinthians | Probabilidade de vitória do União Corinthians: 86.43%
Jogo: Minas vs Basquete Cearense | Resultado: Minas | Probabilidade de vitória do Minas: 94.90%
Jogo: Cruzeiro vs Basquete Cearense | Resultado: Basquete Cearense | Probabilidade de vitória do Cruzeiro: 80.85%
Jogo: São José vs Mogi | Resultado: Mogi | Probabilidade de vitória do São José: 34.80%
Jogo: UNIFACISA vs Botafogo | Resultado: UNIFACISA | Probabilidade de vitória do UNIFACISA: 84.07%
Jogo: Corinthians vs Paulistano | Resultado: Corinthians | Probabilidade de vitória do Corinthians: 73.94%
Jogo: Franca vs Caxias do Sul Basquete | Resultado: Franca | Probabilidade de vitória do Franca: 93.75%
Jogo: Pato Basquete vs Corinthians | Resultado: Corinthians | Probabilidade de vitória do Pato Basquete: 7.00%
Jogo: UNIFACISA vs Flamengo | Resultado: Flamengo | Probabilidade de vitória do UNIFACISA: 41.38%
Jogo: Pinheiros vs Cruzeiro | Resultado: Pinheiros | Probabilidade de vitória do Pinheiros: 92.79%
Jogo: Basket Osasco vs Minas | Resultado: Minas | Probabilidade de vitória do Basket Osasco: 11.67%
Jogo: Franca vs União Corinthians | Resultado: Franca | Probabilidade de vitória do Franca: 93.22%
Jogo: Bauru vs Caxias do Sul Basquete | Resultado: Bauru | Probabilidade de vitória do Bauru: 70.00%
Jogo: Basquete Cearense vs Botafogo | Resultado: Botafogo | Probabilidade de vitória do Basquete Cearense: 43.51%
Jogo: Pinheiros vs Minas | Resultado: Pinheiros | Probabilidade de vitória do Pinheiros: 74.49%
Jogo: Basket Osasco vs Cruzeiro | Resultado: Cruzeiro | Probabilidade de vitória do Basket Osasco: 36.79%
Jogo: Basquete Cearense vs Flamengo | Resultado: Basquete Cearense | Probabilidade de vitória do Basquete Cearense: 9.34%
Jogo: São José vs Corinthians | Resultado: São José | Probabilidade de vitória do São José: 27.14%
Jogo: Brasília vs Pato Basquete | Resultado: Brasília | Probabilidade de vitória do Brasília: 96.32%
Jogo: Mogi vs Paulistano | Resultado: Mogi | Probabilidade de vitória do Mogi: 66.44%
Jogo: Bauru vs União Corinthians | Resultado: União Corinthians | Probabilidade de vitória do Bauru: 68.13%
Jogo: Franca vs Bauru | Resultado: Franca | Probabilidade de vitória do Franca: 90.08%
Jogo: Pato Basquete vs Pinheiros | Resultado: Pinheiros | Probabilidade de vitória do Pato Basquete: 4.91%
Jogo: Caxias do Sul Basquete vs UNIFACISA | Resultado: UNIFACISA | Probabilidade de vitória do Caxias do Sul Basquete: 45.90%
Jogo: União Corinthians vs Basquete Cearense | Resultado: União Corinthians | Probabilidade de vitória do União Corinthians: 86.38%
Jogo: São José vs Botafogo | Resultado: São José | Probabilidade de vitória do São José: 79.16%
Jogo: Paulistano vs Basket Osasco | Resultado: Paulistano | Probabilidade de vitória do Paulistano: 91.43%
Jogo: Cruzeiro vs Minas | Resultado: Cruzeiro | Probabilidade de vitória do Cruzeiro: 24.28%
Jogo: Caxias do Sul Basquete vs Basquete Cearense | Resultado: Caxias do Sul Basquete | Probabilidade de vitória do Caxias do Sul Basquete: 85.32%
Jogo: União Corinthians vs UNIFACISA | Resultado: União Corinthians | Probabilidade de vitória do União Corinthians: 48.07%
Jogo: Paulistano vs Pinheiros | Resultado: Paulistano | Probabilidade de vitória do Paulistano: 32.56%
Jogo: Pato Basquete vs Franca | Resultado: Franca | Probabilidade de vitória do Pato Basquete: 3.12%
Jogo: Minas vs São José | Resultado: Minas | Probabilidade de vitória do Minas: 79.05%
Jogo: Cruzeiro vs São José | Resultado: São José | Probabilidade de vitória do Cruzeiro: 46.14%
Jogo: Basket Osasco vs União Corinthians | Resultado: União Corinthians | Probabilidade de vitória do Basket Osasco: 27.94%
Jogo: Basquete Cearense vs Pato Basquete | Resultado: Pato Basquete | Probabilidade de vitória do Basquete Cearense: 58.65%
Jogo: Botafogo vs Bauru | Resultado: Botafogo | Probabilidade de vitória do Botafogo: 27.60%
Jogo: UNIFACISA vs Brasília | Resultado: UNIFACISA | Probabilidade de vitória do UNIFACISA: 34.39%
Jogo: Mogi vs Flamengo | Resultado: Mogi | Probabilidade de vitória do Mogi: 57.34%
Jogo: Basket Osasco vs Caxias do Sul Basquete | Resultado: Caxias do Sul Basquete | Probabilidade de vitória do Basket Osasco: 29.73%
Jogo: Corinthians vs Bauru | Resultado: Bauru | Probabilidade de vitória do Corinthians: 79.54%
Jogo: São José vs Flamengo | Resultado: Flamengo | Probabilidade de vitória do São José: 33.69%
Jogo: Mogi vs Botafogo | Resultado: Mogi | Probabilidade de vitória do Mogi: 90.95%
Jogo: Pato Basquete vs Basket Osasco | Resultado: Pato Basquete | Probabilidade de vitória do Pato Basquete: 53.31%
Jogo: Basquete Cearense vs Brasília | Resultado: Brasília | Probabilidade de vitória do Basquete Cearense: 7.11%
Jogo: Caxias do Sul Basquete vs União Corinthians | Resultado: Caxias do Sul Basquete | Probabilidade de vitória do Caxias do Sul Basquete: 56.42%
Jogo: Botafogo vs Paulistano | Resultado: Paulistano | Probabilidade de vitória do Botafogo: 21.77%
Jogo: Flamengo vs Corinthians | Resultado: Flamengo | Probabilidade de vitória do Flamengo: 50.88%
Jogo: Bauru vs UNIFACISA | Resultado: UNIFACISA | Probabilidade de vitória do Bauru: 58.35%
Jogo: Cruzeiro vs Mogi | Resultado: Cruzeiro | Probabilidade de vitória do Cruzeiro: 24.45%
Jogo: Brasília vs Basket Osasco | Resultado: Brasília | Probabilidade de vitória do Brasília: 95.49%
Jogo: União Corinthians vs São José | Resultado: União Corinthians | Probabilidade de vitória do União Corinthians: 56.25%
Jogo: Botafogo vs Corinthians | Resultado: Corinthians | Probabilidade de vitória do Botafogo: 12.17%
Jogo: Flamengo vs Paulistano | Resultado: Flamengo | Probabilidade de vitória do Flamengo: 67.54%
Jogo: Minas vs Mogi | Resultado: Minas | Probabilidade de vitória do Minas: 58.78%
Jogo: Bauru vs Basquete Cearense | Resultado: Bauru | Probabilidade de vitória do Bauru: 90.56%
Jogo: Franca vs UNIFACISA | Resultado: Franca | Probabilidade de vitória do Franca: 90.01%
Jogo: Brasília vs Pinheiros | Resultado: Brasília | Probabilidade de vitória do Brasília: 48.92%
Jogo: Caxias do Sul Basquete vs São José | Resultado: São José | Probabilidade de vitória do Caxias do Sul Basquete: 54.10%
Jogo: Franca vs Basquete Cearense | Resultado: Franca | Probabilidade de vitória do Franca: 98.41%
Jogo: Caxias do Sul Basquete vs Mogi | Resultado: Caxias do Sul Basquete | Probabilidade de vitória do Caxias do Sul Basquete: 30.82%
Jogo: Paulistano vs Minas | Resultado: Paulistano | Probabilidade de vitória do Paulistano: 49.96%
Jogo: Botafogo vs Pinheiros | Resultado: Botafogo | Probabilidade de vitória do Botafogo: 8.69%
Jogo: Flamengo vs Basket Osasco | Resultado: Basket Osasco | Probabilidade de vitória do Flamengo: 94.02%
Jogo: Corinthians vs Cruzeiro | Resultado: Corinthians | Probabilidade de vitória do Corinthians: 89.83%
Jogo: Brasília vs Bauru | Resultado: Brasília | Probabilidade de vitória do Brasília: 79.33%
Jogo: UNIFACISA vs Pato Basquete | Resultado: UNIFACISA | Probabilidade de vitória do UNIFACISA: 90.67%
Jogo: União Corinthians vs Mogi | Resultado: União Corinthians | Probabilidade de vitória do União Corinthians: 32.70%
Jogo: Paulistano vs Cruzeiro | Resultado: Cruzeiro | Probabilidade de vitória do Paulistano: 81.47%
Jogo: Botafogo vs Basket Osasco | Resultado: Botafogo | Probabilidade de vitória do Botafogo: 67.76%
Jogo: Flamengo vs Pinheiros | Resultado: Pinheiros | Probabilidade de vitória do Flamengo: 41.56%
Jogo: Corinthians vs Minas | Resultado: Corinthians | Probabilidade de vitória do Corinthians: 66.72%
Jogo: Brasília vs Franca | Resultado: Franca | Probabilidade de vitória do Brasília: 37.37%
Jogo: Corinthians vs União Corinthians | Resultado: Corinthians | Probabilidade de vitória do Corinthians: 85.47%
Jogo: Paulistano vs Caxias do Sul Basquete | Resultado: Caxias do Sul Basquete | Probabilidade de vitória do Paulistano: 76.17%
Jogo: Cruzeiro vs Botafogo | Resultado: Cruzeiro | Probabilidade de vitória do Cruzeiro: 69.73%
Jogo: São José vs Brasília | Resultado: Brasília | Probabilidade de vitória do São José: 27.39%
Jogo: Pinheiros vs Bauru | Resultado: Pinheiros | Probabilidade de vitória do Pinheiros: 84.99%
Jogo: Basket Osasco vs Franca | Resultado: Franca | Probabilidade de vitória do Basket Osasco: 3.83%
Jogo: Minas vs Flamengo | Resultado: Minas | Probabilidade de vitória do Minas: 57.57%
Jogo: Mogi vs Pato Basquete | Resultado: Mogi | Probabilidade de vitória do Mogi: 94.87%
Jogo: UNIFACISA vs Basquete Cearense | Resultado: UNIFACISA | Probabilidade de vitória do UNIFACISA: 90.63%
Jogo: Minas vs Botafogo | Resultado: Minas | Probabilidade de vitória do Minas: 91.03%
Jogo: Paulistano vs União Corinthians | Resultado: União Corinthians | Probabilidade de vitória do Paulistano: 74.55%
Jogo: Cruzeiro vs Flamengo | Resultado: Flamengo | Probabilidade de vitória do Cruzeiro: 23.55%
Jogo: São José vs Pato Basquete | Resultado: Pato Basquete | Probabilidade de vitória do São José: 87.49%
Jogo: Corinthians vs Caxias do Sul Basquete | Resultado: Caxias do Sul Basquete | Probabilidade de vitória do Corinthians: 86.52%
Jogo: Mogi vs Brasília | Resultado: Brasília | Probabilidade de vitória do Mogi: 49.95%
Jogo: Pinheiros vs Franca | Resultado: Pinheiros | Probabilidade de vitória do Pinheiros: 46.81%
Jogo: Basket Osasco vs Bauru | Resultado: Bauru | Probabilidade de vitória do Basket Osasco: 20.39%

In [ ]:
# ====================================================================================
# Simulando a temporada com mini monte carlo
# ====================================================================================
historico_posicoes = []
for i in range(100):  # Simulando 10.000 temporadas
    tabela = {time: 0 for time in elo_26['Time']}  # Inicializando a tabela de vitórias

    for row in nbb_26.itertuples():
        casa = row.Casa
        fora = row.Visitante
        
        elo_casa = elo_26[elo_26['Time'] == casa].iloc[0]['Elo']
        elo_fora = elo_26[elo_26['Time'] == fora].iloc[0]['Elo']
        vtg = (elo_casa + 60) - elo_fora  # Adicionando vantagem de casa de 60 pontos
        
        prob_casa = 1 / (1 + 10 ** ((-vtg) / 400))
        
        vencedor = np.random.choice([casa, fora], p=[prob_casa, 1 - prob_casa])
        tabela[vencedor] += 1

        classificacao = sorted(
            tabela.items(),
            key=lambda x: x[1],
            reverse=True
        )
    historico_posicoes.append(classificacao)

In [13]:
# ====================================================================================
# Observando os resultados da simulação
# ====================================================================================

# Analisando as probabilidades do Brasília
hist_bsb = []

for classificacao in historico_posicoes:
    for posicao, (time, vitorias) in enumerate(classificacao, start=1):
        if time == 'Brasília':
            hist_bsb.append(posicao)
            break


hist_bsb = np.array(hist_bsb)

bsb_campeao = np.sum(hist_bsb == 1) / len(hist_bsb)
bsb_top4 = np.sum(hist_bsb <= 4) / len(hist_bsb)
bsb_playoffs = np.sum(hist_bsb <= 8) / len(hist_bsb) 
print(f"Probabilidade do Brasília ser campeão: {bsb_campeao:.2%}")
print(f"Probabilidade do Brasília ficar entre os 4 primeiros: {bsb_top4:.2%}")
print(f"Probabilidade do Brasília ficar entre os 8 primeiros (playoffs): {bsb_playoffs:.2%}")

Probabilidade do Brasília ser campeão: 17.00%
Probabilidade do Brasília ficar entre os 4 primeiros: 69.00%
Probabilidade do Brasília ficar entre os 8 primeiros (playoffs): 94.00%

In [19]:
# ====================================================================================
# Simulando a temporada com monte carlo com otimizações
# ====================================================================================
elo_dict = dict(zip(elo_26['Time'], elo_26['Elo']))  # Criando um dicionário para acesso rápido aos elos

historico_posicoes = []
for i in range(10000):  # Simulando 10.000 temporadas
    tabela = {time: 0 for time in elo_26['Time']}  # Inicializando a tabela de vitórias

    for row in nbb_26.itertuples():
        casa = row.Casa
        fora = row.Visitante
        
        elo_casa = elo_dict[casa]
        elo_fora = elo_dict[fora]
        vtg = (elo_casa + 60) - elo_fora  # Adicionando vantagem de casa de 60 pontos
        
        prob_casa = 1 / (1 + 10 ** ((-vtg) / 400))
        
        vencedor = np.random.choice([casa, fora], p=[prob_casa, 1 - prob_casa])
        tabela[vencedor] += 1

        classificacao = sorted(
            tabela.items(),
            key=lambda x: x[1],
            reverse=True
        )
        time_alvo = 'Corinthians'  # Substitua pelo time que você deseja analisar
        
        for posicao, (time, vitorias) in enumerate(classificacao, start=1):
            if time == time_alvo:
                historico_posicoes.append(posicao)
                break

In [20]:
# ====================================================================================
# Observando os resultados da simulação
# ====================================================================================

hist_cor = np.array(historico_posicoes)

cor_campeao = np.mean(hist_cor == 1)
cor_top4 = np.mean(hist_cor <= 4)
cor_playoffs = np.mean(hist_cor <= 8)
print(f"Probabilidade do Corinthians ser campeão: {cor_campeao:.2%}")
print(f"Probabilidade do Corinthians ficar entre os 4 primeiros: {cor_top4:.2%}")
print(f"Probabilidade do Corinthians ficar entre os 8 primeiros (playoffs): {cor_playoffs:.2%}")

Probabilidade do Corinthians ser campeão: 6.36%
Probabilidade do Corinthians ficar entre os 4 primeiros: 35.48%
Probabilidade do Corinthians ficar entre os 8 primeiros (playoffs): 68.43%